server:
  port: 8086
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/registered_users_todo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: password

    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-authentication-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true