server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todo_tracker_db
  main:
    allow-circular-references: true

  application:
    name: user-todotracker-service



